## Pointer based registration
pointer:
  tooltip name: drill_tip # Rigid body that is attached to the tip of the tool
  number of points: 5
  name of points:
    - F1
    - F2
    - F3
    - F4
    - F5

    # - Sphere_00
    # - Sphere_01
    # - Sphere_02
    # - Sphere_03
    # - Sphere_04
    # - Sphere_05
    # - Sphere_06
    # - Sphere_07
    # - Sphere_08
    # - Sphere_09
    # - Sphere_10
    # - Sphere_11
    # - Sphere_12
    # - Sphere_13
    # - Sphere_14
    # - Sphere_15
    # - Sphere_16
    # - Sphere_17
    # - Sphere_18
    # - Sphere_19
  object name: TB1011_anatomical_origin
  # object name: TB0904_anatomical_origin
  # object name: TB0914_anatomical_origin
  # object name: DS0913_1_anatomical_origin
  # object name: DS0913_2_anatomical_origin

## Optical Tracker Registration
optical tracker:
  namespace: /atracsys #rostopic name for the optical marker
  name of points:
    - anatomy

## Hand-Eye Regisration
hand eye:
  # Both the robot and the marker status should be published using CRTK
  namespace: /REMS/Research/ #namespace for the robot 
  marker name: atracsys/Anspoch_drill # This name should used for both rostopic name and object name in AMBF
  joint name: dovetail_male
  optical tracker name: Tracker
  resolution: 0.001
  number of points: 1500
  registered HE result:
    # 0811
    # q_rot: 
    #   x: -0.44392565
    #   y: -0.43748763
    #   z: 0.57720114
    #   w: 0.52761105
    # q_dual: 
    #   x: 0.05157883    
    #   y: -0.03933842
    #   z: -0.02773238
    #   w: 0.04111789
    
    # # 0824
    # q_rot: 
    #   x: 0.28250703     
    #   y: -0.34652492
    #   z: 0.88047073
    #   w: 0.1577389
    # q_dual: 
    #   x: 0.04093878     
    #   y: -0.03396216
    #   z: -0.02833392
    #   w: 0.01022549

    # 0824
    # q_rot: 
    #   x: 0.31249885      
    #   y: -0.31309434
    #   z: 0.8859285
    #   w: 0.13945287
    # q_dual: 
    #   x: 0.04779426    
    #   y: -0.01977394
    #   z: -0.02610652
    #   w: 0.0143543

    #0826
    # q_rot: 
    #   x: 0.31819239     
    #   y: -0.31104621
    #   z: 0.87892694
    #   w: 0.1717303
    # q_dual: 
    #   x: 0.03030915    
    #   y: -0.02936303
    #   z: -0.02448269
    #   w: 0.01596162

    #0827
    # q_rot:
    #   x: -0.7758928  
    #   y: -0.2857084   
    #   z: 0.03552252  
    #   w: 0.56133699
    # q_dual:
    #   x: 0.02420084    
    #   y: -0.02888176
    #   z: -0.00910537
    #   w: 0.01932698

    # 0827 Dual
    # q_rot:
    #   x: -0.20573478  
    #   y: 0.8678339
    #   z: 0.40940596  
    #   w: 0.19215694

    # q_dual:
    #   x: -0.0400526      
    #   y: -0.02514503  
    #   z: 0.03460158 
    #   w: -0.00304229

    # 0828
    # q_rot:
    #   x: -0.20493657      
    #   y: 0.86554729
    #   z: 0.41228553 
    #   w: 0.19710286

    # q_dual:
    #   x: -0.0418117          
    #   y: -0.02558465  
    #   z: 0.03405824
    #   w: -0.00236295

    # 0909
    q_rot:
      x: -0.21229946
      y: 0.8618833
      z: 0.41732556 
      w: 0.19474468

    q_dual:
      x: -0.03906011        
      y: -0.02503096  
      z: 0.0335063
      w: -0.00360324  



# ## Pivot calibration
pivot:
  tooltip name: drill_tip
  namespace: /REMS/Research/ #namespace for the robot 
  marker name: atracsys/Anspoch_drill
  resolution: 0.01
  number of points: 150
  registered pivot result:
    # Orignal Point
    # t_tip: 
    #   x: -0.077053
    #   y:  0.150933
    #   z:  0.043711

    # t_tip:
    #   x: 0.0738
    #   z: -0.1486
    #   y: -0.0451

    # 0827
    # t_tip: 
    #   x: -0.07555049605 
    #   y: 0.14830072358  
    #   z: 0.04693415223

    # 0827 Dual
    # t_tip:
    #   x: 0.113366
    #   y: -0.161801
    #   z: 0.084349

    #0828
    # t_tip:
    #   x: 0.11388708842    
    #   y: -0.15785066246
    #   z: 0.08484844486

    # 0909
    # t_tip:
    #   x: 0.112303
    #   y: -0.161753
    #   z:  0.084276

    # 0910 Optical Tracker
    # t_tip:
    #   x: 0.112229
    #   y: -0.161895
    #   z:  0.084108

    # 0910 Rotbot Pivot Calibration
    # t_tip: 
    #   x: 0.070891 
    #   y: -0.061150
    #   z: -0.125319 
    
    # 1011 Rotbot Pivot Calibration
    t_tip: {x: -0.104696, y: 0.142219, z: 0.030938}


